name: Codex Extract-Adapt-Add

on:
  repository_dispatch:
    types: [codex extract-adapt-add]
  workflow_dispatch:

jobs:
  extract-adapt-add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Latest Changes
        run: |
          git config --local user.name "Codex Action Bot"
          git config --local user.email "codex-bot@example.com"
          git pull origin main

      - name: Scan for New Codex Artifacts
        run: |
          echo "Detecting new artifacts for Codex adaptation..."
          if [ -f docs/research-notes.md ]; then
            echo "Found research-notes.md"
            cat docs/research-notes.md
          fi
          if [ -f meta/Living-Codex.json ]; then
            echo "Found Living-Codex.json"
            cat meta/Living-Codex.json
          fi
          if [ -f templates/prompt-examples.md ]; then
            echo "Found prompt-examples.md"
            cat templates/prompt-examples.md
          fi
          if [ -f src/phi-node.py ]; then
            echo "Found phi-node.py"
            cat src/phi-node.py
          fi

      - name: Adapt and Format Artifacts
        run: |
          echo "Formatting and adapting Codex artifacts..."
          # Custom formatting and adaptation logic
          # This step can be expanded for adaptation/cleanup
          # Examples: normalize formatting, extract metadata, update indices

      - name: Commit and Push Changes
        run: |
          git config --local user.name "Codex Action Bot"
          git config --local user.email "codex-bot@example.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Codex auto-import: extract-adapt-add artifacts [repository_dispatch]"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Success Banner
        run: echo "✅ Codex extract-adapt-add workflow completed successfully!"
